# -*- coding: utf-8 -*-
"""youtube.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1oia08F2XVwb0dT5cINfQXJPnQ8MbEZPH

# **Código para analizar los metadatos de YouTube**
"""

import urllib.request as url
import random as rand
rand.seed(12)

"""## **1. Generar links aleatorios de YouTube**"""

def ytlink(seed):
  rand.seed(seed)
  alpha = ['a','b','c','d','e','f','g','h','i','j','k','l','m','n','o','p','q','r','s','t','u','v','w','x','y','z']
  ALPHA = ['A','B','C','D','E','F','G','H','I','J','K','L','M','N','O','P','Q','R','S','T','U','V','W','X','Y','Z']
  num = ['1','2','3','4','5','6','7','8','9','0','-','_']
  pool = [alpha, ALPHA, num]
  youtube = 'https://www.youtube.com/watch?v='
  for i in range(0,11):
    s = rand.randint(0,len(pool)-1)
    ss = rand.randint(0,len(pool[s])-1)
    youtube += pool[s][ss]
  print(youtube)
  return(youtube)

"""## **2. Funciones para extraer el contenido de las urls de YouTube**"""

def getContent(yturl):
  webUrl = url.urlopen(yturl)
  if (webUrl.getcode()!= 200):
    return('Wrong URL!')
  return str(webUrl.read())

def getData(yturl):
  cont = getContent(yturl)
  if (cont == 'Wrong URL!'):
    return('Wrong URL!')

  NameIni = cont.index('<meta name="title" content=') + 27
  NameFin = cont[NameIni:].index('">') + NameIni + 1

  MetaIni = cont.index('<meta name="keywords" content=') + 31
  MetaFin = cont[MetaIni:].index('">') + MetaIni

  if (cont.find('viewCount') > 0):
    ViewsIni = cont.index('viewCount') + 12
    ViewsFin = cont[ViewsIni:].index('"')+ ViewsIni
    data = [yturl, cont[NameIni:NameFin], cont[MetaIni:MetaFin].split(', '), int(cont[ViewsIni:ViewsFin])]
  else:
    data = [yturl, cont[NameIni:NameFin], cont[MetaIni:MetaFin].split(', '), False]
  return(data)

# Se intento generar videos aleatorios, pero al realizar un analisis se 
# descubrio que la probabilidad de generar un video de YouTube al azar
# es del 0.0000000054% 
#
# nextVideo = []
# for i in range(1):
#   print("Video:" + str(i))
#   titulo = '""'
#   while (titulo == '""'):
#     seed = rand.randint(1,1000000)
#     nextVideo = getData(ytlink(seed))
#     titulo = nextVideo[1]
#   videos.append(nextVideo)

links = ['https://www.youtube.com/watch?v=FWaCe9fmsNM', 'https://www.youtube.com/watch?v=iZnLZFRylbs', 'https://www.youtube.com/watch?v=r2geJMK84ME',
         'https://www.youtube.com/watch?v=G86YBWspJVY', 'https://www.youtube.com/watch?v=kleKetOBXC8', 'https://www.youtube.com/watch?v=MCUJNt_rgI8',
         'https://www.youtube.com/watch?v=PEnJbjBuxnw', 'https://www.youtube.com/watch?v=xD-IQaxHcE4', 'https://www.youtube.com/watch?v=a6HKeqWY6T4']
videos = []
for link in links:
  videos.append(getData(link))

videos